# tyro YAML.
!dataclass:TrainConfig
out_dir: gs://uscentral1stuff/gpt_models/gpt_small
train_pattern: gs://uscentral1stuff/openwebtext/train_??.tfrecord
val_pattern: gs://uscentral1stuff/openwebtext/val_??.tfrecord
shuffle_buffer_size: 128
eval_interval: 100
eval_steps: 10
hs_eval_steps: 20
eval_only: False
keep_checkpoints: 0
batch_size: 16
train_steps: 50000
weight_decay: 0.1
grad_clip: 1.0
gradient_accumulation_steps: 1
betas: 
  - 0.9
  - 0.95
learning_rate: !dataclass:CosineDecayScheduleConfig
    init_value: 0.0
    peak_value: 0.001
    warmup_steps: 1000
    decay_steps: 50000
    end_value: 0.00001
wandb: !dataclass:WandbConfig
    entity: evanatyourservice
    project: owt
    mode: online
model: !dataclass:GPTConfig
    num_layers: 8
    num_heads: 8
    num_embeds: 512
