# tyro YAML.
!dataclass:TrainConfig
batch_size: 32
eval_interval: 50
eval_steps: 5
keep_checkpoints: 1
model: !dataclass:GPTConfig
  num_embeds: 32
  num_heads: 2
  num_layers: 1
shuffle_buffer_size: 2
train_pattern: '/Users/evanwalters/owt_10k_data/train_??.tfrecord'
train_steps: 10000
val_pattern: '/Users/evanwalters/owt_10k_data/val_??.tfrecord'
wandb: !dataclass:WandbConfig
  mode: disabled
learning_rate: !dataclass:CosineDecayScheduleConfig
  peak_value: 0.0001