# tyro YAML.
!dataclass:TrainConfig
batch_size: 32
eval_interval: 50
eval_steps: 5
hs_eval_steps: 10
keep_checkpoints: 0
model: !dataclass:GPTConfig
  num_embeds: 32
  num_heads: 2
  num_layers: 1
shuffle_buffer_size: 2
train_steps: 10000
wandb: !dataclass:WandbConfig
  mode: disabled
learning_rate: !dataclass:OptimizerConfig
  peak_value: 0.0001